### ISSUE TITLE
Add comment support

### ISSUE THREAD

**Issue by safield** [elMuso/Dartlight#1]
The dart syntax is missing comment support.

Sublime commands such as 'toggle_comment' do not work using this dart syntax.

Maybe just incorporate this file from the abandoned dart plugin...

https://github.com/theadamlt/SublimeDartHighlighter/blob/master/Preferences/Comments.tmPreferences

**Comment by elMuso** [comment]
Done ! . I was wondering why i could not comment today and checked this . Thanks for the help!
