### ISSUE TITLE
template method does not highlight '<'

### ISSUE THREAD

**Issue by safield** [elMuso/Dartlight#2]
Observe the method hasValue<T> in the following screenshot. The character '<' coloring does not match the '>' coloring.

![dart_syntax_coloring](https://user-images.githubusercontent.com/12876404/60046215-6a07e180-968c-11e9-9e38-854c2df39e5e.png)

**Comment by elMuso** [comment]
Oh didn't noticed it.

Please forgive me for this question, but i don't know the implementation of "<T>" in that function. What is the purpose of <T>? 

It's worth mentioning that i didn't made this. It's a implementation of https://github.com/Dart-Code/Dart-Code/blob/master/syntaxes/dart.json . So if this is not working you might as well try vscode with the dart extension and see if it is not wrking there. If not file an issue there c:
