### ISSUE TITLE
What is the license of this repository ?

### ISSUE THREAD

**Issue by Aelerinya** [elMuso/Dartlight#6]
@elMuso The license file in the repository is really strange. It starts off with the MIT license and then the rest is the end of a GPL license ? Is this a mistake ? What is the proper license of the repository ?

**Comment by elMuso** [comment]
It's supposed to be MIT but i undestand that it's even confusing for me how 2 licenses got mixed

Thanks for pointing that out, i don't know how the license got like that, it's fixed now.
